name: Main Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  vm-job:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test Build.csproj -c Release --no-build --logger trx  --results-directory ./test-results/ /p:CI=true
      env:
        EnableTestLogging: true
